using LankaConnect.Modules.Identity.Contracts; // W4.7.d.2
using LankaConnect.SharedKernel.Identity;
using LankaConnect.BuildingBlocks.Application.Common;
using LankaConnect.BuildingBlocks.Application.Common.Interfaces;
using LankaConnect.Modules.Communications.Domain.Enums;
using LankaConnect.Products.LankaEvents.Domain;
using LankaConnect.Modules.Identity.Domain.DomainEvents;
using LankaConnect.Products.LankaEvents.Domain.DomainEvents;
using LankaConnect.Modules.Identity.Domain.Entities;
using LankaConnect.Modules.Identity.Domain.Repositories;
using LankaConnect.Modules.Identity.Domain.Events;
using LankaConnect.Modules.Communications.Contracts.Email.Helpers;
using LankaConnect.Modules.Communications.Contracts.WhatsApp.Contracts;
using MediatR;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
namespace LankaConnect.Modules.Payments.Application.EventHandlers;

/// <summary>
/// Phase 7A.3: Sends WhatsApp notification when payment is completed for a paid event.
/// Parallel to PaymentCompletedEventHandler (email). Email handler is UNTOUCHED.
/// Uses fire-and-forget with IServiceScopeFactory [FIX C6].
/// </summary>
public class PaymentCompletedWhatsAppHandler : INotificationHandler<DomainEventNotification<PaymentCompletedEvent>>
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<PaymentCompletedWhatsAppHandler> _logger;

    public PaymentCompletedWhatsAppHandler(
        IServiceScopeFactory scopeFactory,
        ILogger<PaymentCompletedWhatsAppHandler> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    public Task Handle(DomainEventNotification<PaymentCompletedEvent> notification, CancellationToken cancellationToken)
    {
        var domainEvent = notification.DomainEvent;
        var eventId = domainEvent.EventId;
        var registrationId = domainEvent.RegistrationId;
        var userId = domainEvent.UserId;
        var amountPaid = domainEvent.AmountPaid;

        _logger.LogInformation(
            "[Phase 7A] WhatsApp PaymentCompleted START: EventId={EventId}, RegistrationId={RegistrationId}, Amount={Amount}",
            eventId, registrationId, amountPaid);

        // Only send if we have a UserId (registered user with potential WhatsApp preferences)
        if (!userId.HasValue)
        {
            _logger.LogInformation("[Phase 7A] WhatsApp PaymentCompleted SKIPPED: No UserId (anonymous payment)");
            return Task.CompletedTask;
        }

        var capturedUserId = userId.Value;

        _ = Task.Run(async () =>
        {
            try
            {
                using var scope = _scopeFactory.CreateScope();
                var whatsAppService = scope.ServiceProvider.GetRequiredService<IWhatsAppService>();
                var identityQueries = scope.ServiceProvider.GetRequiredService<IIdentityQueries>();
                var eventRepository = scope.ServiceProvider.GetRequiredService<IEventRepository>();

                var user = await identityQueries.GetUserByIdAsync(capturedUserId, CancellationToken.None);
                if (user == null)
                {
                    _logger.LogWarning("[Phase 7A] WhatsApp PaymentCompleted: User not found - UserId={UserId}", capturedUserId);
                    return;
                }

                var @event = await eventRepository.GetByIdAsync(eventId, CancellationToken.None);
                if (@event == null)
                {
                    _logger.LogWarning("[Phase 7A] WhatsApp PaymentCompleted: Event not found - EventId={EventId}", eventId);
                    return;
                }

                var location = @event.Location?.Address != null
                    ? $"{@event.Location.Address.Street}, {@event.Location.Address.City}".Trim(',', ' ')
                    : "Online Event";

                // Ticket code is generated by ITicketService after payment; use registration ID as reference
                var ticketCode = registrationId.ToString()[..8].ToUpperInvariant();

                var parameters = new Dictionary<string, string>
                {
                    { WhatsAppTemplateContract.Common.UserName, $"{user.FirstName} {user.LastName}" },
                    { WhatsAppTemplateContract.Common.EventTitle, @event.Title.Value },
                    { WhatsAppTemplateContract.Registration.TicketCode, ticketCode },
                    { WhatsAppTemplateContract.Common.EventDate, EmailDateTimeHelper.FormatEventDate(@event.StartDate, @event.TimeZoneId) },
                    { WhatsAppTemplateContract.Common.EventTime, EmailDateTimeHelper.FormatEventTime(@event.StartDate, @event.TimeZoneId) },
                    { WhatsAppTemplateContract.Common.EventLocation, location },
                    { WhatsAppTemplateContract.Common.EventUrl, $"https://lankaconnect.com/events/{eventId}" }
                };

                var result = await whatsAppService.SendTemplateMessageAsync(
                    capturedUserId,
                    WhatsAppTemplateContract.TemplateNames.EventTicketConfirmation,
                    parameters,
                    WhatsAppNotificationType.Payment,
                    eventId,
                    registrationId,
                    CancellationToken.None);

                if (result.IsSuccess && !result.Value.WasSkipped)
                {
                    _logger.LogInformation("[Phase 7A] WhatsApp PaymentCompleted SENT: EventId={EventId}, UserId={UserId}", eventId, capturedUserId);
                }
                else if (result.IsSuccess && result.Value.WasSkipped)
                {
                    _logger.LogInformation("[Phase 7A] WhatsApp PaymentCompleted SKIPPED: {Reason}", result.Value.SkipReason);
                }
                else
                {
                    _logger.LogWarning("[Phase 7A] WhatsApp PaymentCompleted FAILED: {Errors}", string.Join(", ", result.Errors));
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "[Phase 7A] WhatsApp PaymentCompleted EXCEPTION: EventId={EventId}, UserId={UserId}", eventId, capturedUserId);
            }
        }, CancellationToken.None);

        return Task.CompletedTask;
    }
}
