// <auto-generated />
using System;
using System.Collections.Generic;
using LankaConnect.Domain.Events.ValueObjects;
using LankaConnect.Modules.Forms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LankaConnect.Modules.Forms.Infrastructure.Migrations
{
    [DbContext(typeof(FormsDbContext))]
    [Migration("20260607125345_Baseline_Forms")]
    partial class Baseline_Forms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("forms")
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LankaConnect.BuildingBlocks.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerializedResponse")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "forms");
                });

            modelBuilder.Entity("LankaConnect.BuildingBlocks.Infrastructure.Outbox.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginalOutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_outbox_dead_letter_dead_lettered_at");

                    b.HasIndex("OriginalOutboxId")
                        .HasDatabaseName("ix_outbox_dead_letter_original_outbox_id");

                    b.ToTable("outbox_dead_letter", "forms");
                });

            modelBuilder.Entity("LankaConnect.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending_occurred_at")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("outbox", "forms");
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.Entities.FormAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FormQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_question_id");

                    b.Property<Guid>("FormResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_response_id");

                    b.Property<string>("QuestionTextSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question_text_snapshot");

                    b.Property<IReadOnlyList<Guid>>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_option_ids");

                    b.Property<IReadOnlyList<string>>("SelectedOptionTextSnapshots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_option_text_snapshots");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormQuestionId")
                        .HasDatabaseName("ix_form_answers_form_question_id");

                    b.HasIndex("FormResponseId")
                        .HasDatabaseName("ix_form_answers_form_response_id");

                    b.ToTable("form_answers", "events");
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.Entities.FormQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EventFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_form_id");

                    b.Property<string>("HelpText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<IReadOnlyList<QuestionOption>>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventFormId")
                        .HasDatabaseName("ix_form_questions_event_form_id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_form_questions_sort_order");

                    b.ToTable("form_questions", "events");
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.Entities.FormResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("access_token_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EventFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_form_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("RespondentEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("respondent_email");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("respondent_name");

                    b.Property<Guid?>("RespondentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("respondent_user_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_form_responses_access_token_hash");

                    b.HasIndex("EventFormId")
                        .HasDatabaseName("ix_form_responses_event_form_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_form_responses_event_id");

                    b.HasIndex("RespondentEmail")
                        .HasDatabaseName("ix_form_responses_respondent_email");

                    b.HasIndex("RespondentUserId")
                        .HasDatabaseName("ix_form_responses_respondent_user_id");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_form_responses_submitted_at");

                    b.HasIndex("EventFormId", "RespondentUserId")
                        .HasDatabaseName("ix_form_responses_event_form_id_respondent_user_id");

                    b.ToTable("form_responses", "events");
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.EventForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAttendeesToViewResponses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_attendees_to_view_responses");

                    b.Property<bool>("AllowMultipleResponses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_multiple_responses");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("HasResponses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_responses");

                    b.Property<int?>("MaxResponses")
                        .HasColumnType("integer")
                        .HasColumnName("max_responses");

                    b.Property<DateTime?>("ResponseDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_deadline");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_forms_event_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_event_forms_status");

                    b.ToTable("event_forms", "events");
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.Entities.FormAnswer", b =>
                {
                    b.HasOne("LankaConnect.Modules.Forms.Domain.Entities.FormResponse", null)
                        .WithMany("Answers")
                        .HasForeignKey("FormResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.Entities.FormQuestion", b =>
                {
                    b.HasOne("LankaConnect.Modules.Forms.Domain.EventForm", null)
                        .WithMany("Questions")
                        .HasForeignKey("EventFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.Entities.FormResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LankaConnect.Modules.Forms.Domain.EventForm", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
