using LankaConnect.BuildingBlocks.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LankaConnect.BuildingBlocks.Infrastructure.Tests;

/// <summary>
/// W1B verification: IConcurrencyToken auto-application by BaseDbContext.
/// </summary>
/// <remarks>
/// The InMemory provider does not enforce concurrency tokens at runtime — we
/// verify EF Core metadata (IsRowVersion / IsConcurrencyToken) instead.
/// Full runtime enforcement is exercised by per-Capability Testcontainers
/// integration tests in Wave 4.
/// </remarks>
public sealed class BaseDbContextConcurrencyTokenTests
{
    [Fact]
    public void OnModelCreating_AutoAppliesIsRowVersion_ToConcurrencyTokenEntities()
    {
        var (db, _) = TestDbContextBuilder.Build();

        var entityType = db.Model.FindEntityType(typeof(ConcurrencyTokenEntity));
        entityType.Should().NotBeNull();

        var rowVersionProperty = entityType!.FindProperty(nameof(IConcurrencyToken.RowVersion));
        rowVersionProperty.Should().NotBeNull();

        rowVersionProperty!.IsConcurrencyToken.Should().BeTrue(
            "BaseDbContext.OnModelCreating must auto-apply IsRowVersion (sets IsConcurrencyToken=true) for IConcurrencyToken entities");
        rowVersionProperty.ValueGenerated.Should().Be(ValueGenerated.OnAddOrUpdate,
            "RowVersion must be generated by the database on every write");
    }

    [Fact]
    public void OnModelCreating_DoesNotApplyConcurrencyToken_ToNonConcurrencyEntities()
    {
        var (db, _) = TestDbContextBuilder.Build();

        var plainEntityType = db.Model.FindEntityType(typeof(PlainEntity));
        plainEntityType.Should().NotBeNull();

        // PlainEntity has no IConcurrencyToken — must NOT have any concurrency-token property.
        var concurrencyTokenProperties = plainEntityType!.GetProperties()
            .Where(p => p.IsConcurrencyToken);
        concurrencyTokenProperties.Should().BeEmpty(
            "non-IConcurrencyToken entities must not get any concurrency token applied");
    }
}
