// <auto-generated />
using System;
using System.Collections.Generic;
using LankaConnect.Modules.Communications.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LankaConnect.Modules.Communications.Infrastructure.Migrations
{
    [DbContext(typeof(CommunicationsDbContext))]
    partial class CommunicationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communications")
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LankaConnect.BuildingBlocks.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerializedResponse")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "communications");
                });

            modelBuilder.Entity("LankaConnect.BuildingBlocks.Infrastructure.Outbox.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginalOutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_outbox_dead_letter_dead_lettered_at");

                    b.HasIndex("OriginalOutboxId")
                        .HasDatabaseName("ix_outbox_dead_letter_original_outbox_id");

                    b.ToTable("outbox_dead_letter", "communications");
                });

            modelBuilder.Entity("LankaConnect.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_pending_occurred_at")
                        .HasFilter("\"ProcessedAt\" IS NULL");

                    b.ToTable("outbox", "communications");
                });

            modelBuilder.Entity("LankaConnect.Modules.Communications.Domain.Entities.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double?>("BackoffMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("BypassReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<int>("ConcurrentAccessAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CulturalContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("cultural_context");

                    b.Property<bool>("CulturalDelayBypassed")
                        .HasColumnType("boolean");

                    b.Property<string>("CulturalDelayReason")
                        .HasColumnType("text");

                    b.Property<bool>("CulturalTimingOptimized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<bool>("DeliveryConfirmationReceived")
                        .HasColumnType("boolean");

                    b.Property<bool>("DiasporaOptimized")
                        .HasColumnType("boolean");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FestivalContext")
                        .HasColumnType("text");

                    b.Property<bool>("GeographicOptimization")
                        .HasColumnType("boolean");

                    b.Property<int?>("GeographicRegion")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAllRecipientsDelivered")
                        .HasColumnType("boolean");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<DateTime?>("LastStateTransition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LocalizedSendTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateTime?>("OptimalSendTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermanentFailureReason")
                        .HasColumnType("text");

                    b.Property<string>("PostponementReason")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RecipientStatuses")
                        .HasColumnType("jsonb")
                        .HasColumnName("recipient_statuses");

                    b.Property<bool>("ReligiousObservanceConsidered")
                        .HasColumnType("boolean");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("RetryStrategy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SendingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetTimezone")
                        .HasColumnType("text");

                    b.Property<string>("TemplateData")
                        .HasColumnType("jsonb")
                        .HasColumnName("template_data");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_name");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<List<string>>("_bccRecipients")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bcc_emails");

                    b.Property<List<string>>("_ccRecipients")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cc_emails");

                    b.Property<List<string>>("_recipients")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("to_emails");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmailMessages_CreatedAt");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_EmailMessages_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EmailMessages_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_EmailMessages_Type");

                    b.HasIndex("RetryCount", "Status")
                        .HasDatabaseName("IX_EmailMessages_RetryCount_Status");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_EmailMessages_Status_NextRetryAt");

                    b.ToTable("email_messages", "communications");
                });

            modelBuilder.Entity("LankaConnect.Modules.Communications.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("HtmlTemplate")
                        .HasColumnType("text")
                        .HasColumnName("html_template");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_template");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.Property<string>("TextTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_template");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_EmailTemplates_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmailTemplates_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_EmailTemplates_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailTemplates_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_EmailTemplates_Type");

                    b.HasIndex("Category", "IsActive")
                        .HasDatabaseName("IX_EmailTemplates_Category_IsActive");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("IX_EmailTemplates_Type_IsActive");

                    b.ToTable("email_templates", "communications");
                });

            modelBuilder.Entity("LankaConnect.Modules.Communications.Domain.Entities.UserEmailPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMarketing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_marketing");

                    b.Property<bool>("AllowNewsletters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_newsletters");

                    b.Property<bool>("AllowNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_notifications");

                    b.Property<bool>("AllowTransactional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_transactional");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PreferredLanguage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en-US")
                        .HasColumnName("preferred_language");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AllowMarketing")
                        .HasDatabaseName("IX_UserEmailPreferences_AllowMarketing");

                    b.HasIndex("AllowNotifications")
                        .HasDatabaseName("IX_UserEmailPreferences_AllowNotifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UserEmailPreferences_CreatedAt");

                    b.HasIndex("PreferredLanguage")
                        .HasDatabaseName("IX_UserEmailPreferences_PreferredLanguage");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserEmailPreferences_UserId_Unique");

                    b.ToTable("user_email_preferences", "communications");
                });

            modelBuilder.Entity("LankaConnect.Modules.Communications.Domain.Entities.EmailMessage", b =>
                {
                    b.OwnsOne("LankaConnect.Modules.Communications.Domain.ValueObjects.EmailSubject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("EmailMessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subject");

                            b1.HasKey("EmailMessageId");

                            b1.ToTable("email_messages", "communications");

                            b1.WithOwner()
                                .HasForeignKey("EmailMessageId");
                        });

                    b.OwnsOne("LankaConnect.Modules.Communications.Domain.ValueObjects.UserEmail", "FromEmail", b1 =>
                        {
                            b1.Property<Guid>("EmailMessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("from_email");

                            b1.HasKey("EmailMessageId");

                            b1.ToTable("email_messages", "communications");

                            b1.WithOwner()
                                .HasForeignKey("EmailMessageId");
                        });

                    b.Navigation("FromEmail")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
