// <auto-generated />
using System;
using System.Collections.Generic;
using LankaConnect.Products.LankaEvents.Domain.ValueObjects;
using LankaConnect.SPLIT_PER_ENTITY;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LankaConnect.SPLIT_PER_ENTITY.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304000000_AddLinkedUserIdForeignKeyAndIndex")]
    partial class AddLinkedUserIdForeignKeyAndIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only uses raw SQL statements (FK constraint + index).
            // No model changes — inherits full model from previous snapshot.
            // The AppDbContextModelSnapshot.cs reflects the current model state.
        }
    }
}
