/**
 * Slice 6 / Slice 7: shared geometry parsers for VenueLayoutDto rendering.
 *
 * The domain persists geometry as JSON strings (shape-specific schemas —
 * see VenueZone.Geometry, VenueTable.Geometry, VenueDecoration.Geometry).
 * Both LayoutPreview (SVG) and SeatPickerKonva (react-konva) need to read
 * those blobs, and they must degrade identically when geometry is missing
 * or malformed (organizers can hand-edit these fields in the canvas editor,
 * and the domain default is `"{}"`).
 *
 * Keeping the parsers in one file means:
 *   - One shared contract for what "valid geometry" means per shape.
 *   - A future shape addition (e.g. Ellipse) touches one file, not two.
 *   - Tolerant parsing never throws — callers fall back to placeholders.
 */

export interface RectGeom {
  x: number;
  y: number;
  width: number;
  height: number;
  rotation?: number;
}

export interface CurveGeom {
  centerX: number;
  centerY: number;
  radius: number;
  startAngleDeg: number;
  sweepAngleDeg: number;
  rowCount?: number;
}

export interface RoundTableGeom {
  centerX: number;
  centerY: number;
  radius: number;
}

export interface RectTableGeom {
  centerX: number;
  centerY: number;
  width: number;
  height: number;
  rotation?: number;
}

/**
 * Best-effort JSON.parse that never throws. Returns `null` for:
 *   - null / undefined / empty input
 *   - non-object payloads (strings, numbers, arrays)
 *   - syntactically invalid JSON
 */
function tryParse<T extends object>(raw: string | null | undefined): T | null {
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null;
    return parsed as T;
  } catch {
    return null;
  }
}

/** Returns a rect-shape payload or null if missing/invalid. */
export function parseRectGeom(raw: string | null | undefined): RectGeom | null {
  const parsed = tryParse<RectGeom>(raw);
  if (!parsed) return null;
  if (
    typeof parsed.x !== 'number' ||
    typeof parsed.y !== 'number' ||
    typeof parsed.width !== 'number' ||
    typeof parsed.height !== 'number'
  ) {
    return null;
  }
  return parsed;
}

/** Returns a curve-shape payload or null. Curve draws an arc. */
export function parseCurveGeom(raw: string | null | undefined): CurveGeom | null {
  const parsed = tryParse<CurveGeom>(raw);
  if (!parsed) return null;
  if (
    typeof parsed.centerX !== 'number' ||
    typeof parsed.centerY !== 'number' ||
    typeof parsed.radius !== 'number' ||
    typeof parsed.startAngleDeg !== 'number' ||
    typeof parsed.sweepAngleDeg !== 'number'
  ) {
    return null;
  }
  return parsed;
}

/** Returns a round-table payload or null. */
export function parseRoundTableGeom(raw: string | null | undefined): RoundTableGeom | null {
  const parsed = tryParse<RoundTableGeom>(raw);
  if (!parsed) return null;
  if (
    typeof parsed.centerX !== 'number' ||
    typeof parsed.centerY !== 'number' ||
    typeof parsed.radius !== 'number'
  ) {
    return null;
  }
  return parsed;
}

/** Returns a rect-table payload or null. */
export function parseRectTableGeom(raw: string | null | undefined): RectTableGeom | null {
  const parsed = tryParse<RectTableGeom>(raw);
  if (!parsed) return null;
  if (
    typeof parsed.centerX !== 'number' ||
    typeof parsed.centerY !== 'number' ||
    typeof parsed.width !== 'number' ||
    typeof parsed.height !== 'number'
  ) {
    return null;
  }
  return parsed;
}

// ────────────────────────────────────────────────────────────────────────
// Seat position computation
// ────────────────────────────────────────────────────────────────────────
//
// The domain persists per-seat X/Y only for seats the canvas editor has
// placed explicitly (Slice 8). Today, seats generated by the preset factory
// or GenerateTheaterSeats / GenerateRoundTableSeats / GenerateRectTableSeats
// carry Row + Number (or AngleDeg for round tables) but no canvas
// coordinates. The SeatPicker therefore needs a deterministic derivation
// from the zone/table geometry + each seat's structural info.
//
// These helpers are shared between LayoutPreview (Slice 6, SVG) and
// SeatPickerKonva (Slice 7, react-konva) so the two renderers can never
// drift into showing seats in different places.

export interface ComputedSeatPoint {
  seatId: string;
  x: number;
  y: number;
  /** Suggested seat circle radius for the renderer. */
  r: number;
}

interface ZoneSeatLike {
  id: string;
  row: string;
  number: number;
  isEnabled?: boolean;
}

interface RoundTableSeatLike {
  id: string;
  number: number;
  angleDeg?: number | null;
}

interface RectTableSeatLike {
  id: string;
  number: number;
}

/**
 * Lays out zone seats in a row-major grid inside the zone's rect. Groups by
 * `row` (case-insensitive), sorts rows lexicographically, sorts seats by
 * `number` within each row. Padding: 10% horizontal inset, 12% top / 8%
 * bottom vertical inset — leaves room for the zone name label at the top.
 */
export function computeRectZoneSeatPositions(
  seats: ZoneSeatLike[],
  zoneGeom: RectGeom,
): ComputedSeatPoint[] {
  if (seats.length === 0) return [];

  const rows = new Map<string, ZoneSeatLike[]>();
  for (const s of seats) {
    const key = (s.row ?? '').toUpperCase();
    if (!rows.has(key)) rows.set(key, []);
    rows.get(key)!.push(s);
  }
  const rowLabels = Array.from(rows.keys()).sort();
  const rowCount = rowLabels.length;
  const maxCols = Math.max(...Array.from(rows.values()).map((r) => r.length), 1);

  const padX = zoneGeom.width * 0.1;
  const padTop = zoneGeom.height * 0.12;
  const padBottom = zoneGeom.height * 0.08;
  const usableWidth = zoneGeom.width - padX * 2;
  const usableHeight = zoneGeom.height - padTop - padBottom;

  const colWidth = usableWidth / maxCols;
  const rowHeight = rowCount > 0 ? usableHeight / rowCount : 0;
  // Seat radius ~ 40% of the smaller cell dimension, floor at 4 and cap at 12
  // so very dense grids still render distinct dots.
  const r = Math.max(4, Math.min(12, Math.floor(Math.min(colWidth, rowHeight) * 0.4)));

  const result: ComputedSeatPoint[] = [];
  for (let i = 0; i < rowLabels.length; i++) {
    const rowSeats = [...rows.get(rowLabels[i])!].sort((a, b) => a.number - b.number);
    for (const seat of rowSeats) {
      // `number` is 1-based in the domain.
      const col = Math.max(0, seat.number - 1);
      const x = zoneGeom.x + padX + col * colWidth + colWidth / 2;
      const y = zoneGeom.y + padTop + i * rowHeight + rowHeight / 2;
      result.push({ seatId: seat.id, x, y, r });
    }
  }
  return result;
}

/**
 * Radial layout for round-table seats. When a seat carries an
 * `angleDeg` (the domain generator populates this for GenerateRoundTable),
 * use it verbatim so the canvas editor can later rotate individual seats.
 * Otherwise fall back to evenly-distributed 360°/N.
 */
export function computeRoundTableSeatPositions(
  seats: RoundTableSeatLike[],
  tableGeom: RoundTableGeom,
): ComputedSeatPoint[] {
  if (seats.length === 0) return [];
  const n = seats.length;
  const r = Math.max(5, Math.min(12, tableGeom.radius * 0.22));
  const ringR = tableGeom.radius + r + 3;
  return seats.map((s, i) => {
    const angleDeg = typeof s.angleDeg === 'number' ? s.angleDeg : (360 / n) * i;
    const rad = (angleDeg * Math.PI) / 180;
    return {
      seatId: s.id,
      x: tableGeom.centerX + ringR * Math.cos(rad),
      y: tableGeom.centerY + ringR * Math.sin(rad),
      r,
    };
  });
}

/**
 * Perimeter layout for square / rect table seats — mirrors the domain's
 * GenerateRectTableSeats side-distribution (top → right → bottom → left,
 * remainder filling long sides first). Seats are placed on the outer edge
 * so the rect face stays readable as the table surface.
 */
export function computeRectTableSeatPositions(
  seats: RectTableSeatLike[],
  tableGeom: RectTableGeom,
): ComputedSeatPoint[] {
  if (seats.length === 0) return [];
  const n = seats.length;
  const perSide = Math.floor(n / 4);
  const remainder = n % 4;
  const sideCounts = [
    perSide + (remainder > 0 ? 1 : 0), // top
    perSide + (remainder > 1 ? 1 : 0), // right
    perSide + (remainder > 2 ? 1 : 0), // bottom
    perSide,                           // left
  ];

  const r = Math.max(5, Math.min(11, Math.min(tableGeom.width, tableGeom.height) * 0.18));
  const halfW = tableGeom.width / 2;
  const halfH = tableGeom.height / 2;

  const sorted = [...seats].sort((a, b) => a.number - b.number);
  const out: ComputedSeatPoint[] = [];
  let idx = 0;

  for (let side = 0; side < 4; side++) {
    const count = sideCounts[side];
    for (let i = 0; i < count; i++) {
      const seat = sorted[idx++];
      if (!seat) break;
      // Evenly distribute along the side with a small outside offset.
      const t = (i + 1) / (count + 1);
      let x = 0;
      let y = 0;
      if (side === 0) {
        // Top side (above the table)
        x = tableGeom.centerX - halfW + tableGeom.width * t;
        y = tableGeom.centerY - halfH - r - 2;
      } else if (side === 1) {
        // Right side
        x = tableGeom.centerX + halfW + r + 2;
        y = tableGeom.centerY - halfH + tableGeom.height * t;
      } else if (side === 2) {
        // Bottom side
        x = tableGeom.centerX - halfW + tableGeom.width * (1 - t);
        y = tableGeom.centerY + halfH + r + 2;
      } else {
        // Left side
        x = tableGeom.centerX - halfW - r - 2;
        y = tableGeom.centerY - halfH + tableGeom.height * (1 - t);
      }
      out.push({ seatId: seat.id, x, y, r });
    }
  }
  return out;
}

/**
 * Shared color palette for decoration kinds. Both LayoutPreview and the
 * SeatPicker's Konva renderer use these so the organizer's preview and the
 * attendee-facing picker stay visually consistent.
 */
export const decorationStyle = (kind: string): {
  fill: string;
  stroke: string;
  label: string | null;
  labelColor: string;
} => {
  switch (kind) {
    case 'Stage':
      return { fill: '#1f2937', stroke: '#111827', label: 'STAGE', labelColor: '#f9fafb' };
    case 'DanceFloor':
      return { fill: '#fef3c7', stroke: '#f59e0b', label: 'Dance Floor', labelColor: '#b45309' };
    case 'Aisle':
      return { fill: '#e5e7eb', stroke: '#9ca3af', label: null, labelColor: '#4b5563' };
    case 'Door':
      return { fill: '#dbeafe', stroke: '#3b82f6', label: 'Door', labelColor: '#1e40af' };
    case 'Wall':
      return { fill: '#9ca3af', stroke: '#4b5563', label: null, labelColor: '#111827' };
    case 'Text':
      return { fill: 'transparent', stroke: '#9ca3af', label: null, labelColor: '#111827' };
    case 'Image':
      return { fill: '#f3f4f6', stroke: '#9ca3af', label: 'Image', labelColor: '#4b5563' };
    default:
      return { fill: '#f3f4f6', stroke: '#9ca3af', label: null, labelColor: '#4b5563' };
  }
};
